pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo ' Cloning repository...'
                git branch: 'main',
                    credentialsId: 'github-credentials',  
                    url: 'https://github.com/ikgoomophuting-del/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo ' Installing dependencies...'
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt   
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo ' Running tests with pytest...'
                sh '''
                    . venv/bin/activate
                    pytest --maxfail=1 --disable-warnings -q \
                        --junitxml=reports/test-results.xml || true
                '''
            }
            post {
                always {
                    echo ' Publishing test results...'
                    junit 'reports/test-results.xml'
                }
            }
        }
    }

    post {
        success { echo ' Jenkins pipeline executed successfully!' }
        failure { echo ' Pipeline failed — check the logs.' }
    }
}
