name: Django CI - Code Quality and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      DATABASE_URL: mysql://test_user:test_pass@127.0.0.1:3306/test_db
      PYTHONUNBUFFERED: 1

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4

      - name:  Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name:  Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install flake8 coverage pytest pytest-django

      - name:  Lint with flake8
        run: |
          source venv/bin/activate
          echo "Running flake8 lint checks..."
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 messaging_app --count --max-complexity=10 --max-line-length=88 --statistics

      - name:  Run Django tests with coverage
        run: |
          source venv/bin/activate
          echo "Running Django tests..."
          coverage run manage.py test
          coverage report -m
          coverage xml

      - name:  Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
