version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_pass
    volumes:
      - db_data:/var/lib/mysql  # ✅ Persists MySQL data
    ports:
      - "3306:3306"
    env_file:
      - .env

  web:
    build: .
    container_name: messaging_web
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

# ✅ Declare the named volume to persist MySQL data
volumes:
  db_data:
